# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

currencies = 
  Currency.create([
    { name: "Afghani", code: "AFN", minor_unit: 2 },
    { name: "Algerian Dinar", code: "DZD", minor_unit: 2 },
    { name: "Argentine Peso", code: "ARS", minor_unit: 2 },
    { name: "Armenian Dram", code: "AMD", minor_unit: 2 },
    { name: "Aruban Florin", code: "AWG", minor_unit: 2 },
    { name: "Australian Dollar", code: "AUD", minor_unit: 2 },
    { name: "Azerbaijanian Manat", code: "AZN", minor_unit: 2 },
    { name: "Bahamian Dollar", code: "BSD", minor_unit: 2 },
    { name: "Bahraini Dinar", code: "BHD", minor_unit: 3 },
    { name: "Baht", code: "THB", minor_unit: 2 },
    { name: "Balboa", code: "PAB",  minor_unit: 2 },
    { name: "Barbados Dollar", code: "BBD", minor_unit: 2 },
    { name: "Belarussian Ruble", code: "BYR", minor_unit: 0 },
    { name: "Belize Dollar", code: "BZD", minor_unit: 2 },
    { name: "Bermudian Dollar", code: "BMD", minor_unit: 2 },
    { name: "Bolivar", code: "VEF", minor_unit: 2 },
    { name: "Boliviano", code: "BOB", minor_unit: 2 },
    { name: "Brazilian Real", code: "BRL", minor_unit: 2 },
    { name: "Brunei Dollar", code: "BND", minor_unit: 2 },
    { name: "Bulgarian Lev", code: "BGN", minor_unit: 2 },
    { name: "Burundi Franc", code: "BIF", minor_unit: 0 },
    { name: "Canadian Dollar", code: "CAD", minor_unit: 2 },
    { name: "Cape Verde Escudo", code: "CVE", minor_unit: 2 },
    { name: "Cayman Islands Dollar", code: "KYD", minor_unit: 2 },
    { name: "CFA Franc BCEAO", code: "XOF", minor_unit: 0 },
    { name: "CFA Franc BEAC", code: "XAF", minor_unit: 0 },
    { name: "CFP Franc", code: "XPF",  minor_unit: 0 },
    { name: "Chilean Peso", code: "CLP", minor_unit: 0 },
    { name: "Colombian Peso", code: "COP", minor_unit: 2 },
    { name: "Comoro Franc", code: "KMF", minor_unit: 0 },
    { name: "Congolese Franc", code: "CDF", minor_unit: 2 },
    { name: "Convertible Mark", code: "BAM", minor_unit: 2 },
    { name: "Cordoba Oro", code: "NIO",  minor_unit: 2 },
    { name: "Costa Rican Colon", code: "CRC", minor_unit: 2 },
    { name: "Croatian Kuna", code: "HRK", minor_unit: 2 },
    { name: "Cuban Peso", code: "CUP", minor_unit: 2 },
    { name: "Czech Koruna", code: "CZK", minor_unit: 2 },
    { name: "Dalasi", code: "GMD", minor_unit: 2 },
    { name: "Danish Krone", code: "DKK", minor_unit: 2 },
    { name: "Denar", code: "MKD", minor_unit: 2 },
    { name: "Djibouti Franc", code: "DJF", minor_unit: 0 },
    { name: "Dobra", code: "STD", minor_unit: 2 },
    { name: "Dominican Peso", code: "DOP", minor_unit: 2 },
    { name: "Dong", code: "VND", minor_unit: 0 },
    { name: "East Caribbean Dollar", code: "XCD", minor_unit: 2 },
    { name: "Egyptian Pound", code: "EGP", minor_unit: 2 },
    { name: "El Salvador Colon", code: "SVC", minor_unit: 2 },
    { name: "Ethiopian Birr", code: "ETB", minor_unit: 2 },
    { name: "Euro", code: "EUR", minor_unit: 2 },
    { name: "Falkland Islands Pound", code: "FKP", minor_unit: 2 },
    { name: "Fiji Dollar", code: "FJD", minor_unit: 2 },
    { name: "Forint", code: "HUF", minor_unit: 2 },
    { name: "Ghana Cedi", code: "GHS", minor_unit: 2 },
    { name: "Gibraltar Pound", code: "GIP", minor_unit: 2 },
    { name: "Gourde", code: "HTG", minor_unit: 2 },
    { name: "Guarani", code: "PYG",  minor_unit: 0 },
    { name: "Guinea Franc", code: "GNF", minor_unit: 0 },
    { name: "Guyana Dollar", code: "GYD", minor_unit: 2 },
    { name: "Hong Kong Dollar", code: "HKD", minor_unit: 2 },
    { name: "Hryvnia", code: "UAH", minor_unit: 2 },
    { name: "Iceland Krona", code: "ISK", minor_unit: 0 },
    { name: "Indian Rupee", code: "INR", minor_unit: 2 },
    { name: "Iranian Rial", code: "IRR", minor_unit: 2 },
    { name: "Iraqi Dinar", code: "IQD", minor_unit: 3 },
    { name: "Jamaican Dollar", code: "JMD", minor_unit: 2 },
    { name: "Jordanian Dinar", code: "JOD", minor_unit: 3 },
    { name: "Kenyan Shilling", code: "KES", minor_unit: 2 },
    { name: "Kina", code: "PGK",  minor_unit: 2 },
    { name: "Kip", code: "LAK", minor_unit: 2 },
    { name: "Kuwaiti Dinar", code: "KWD", minor_unit: 3 },
    { name: "Kwacha", code: "MWK", minor_unit: 2 },
    { name: "Kwanza", code: "AOA", minor_unit: 2 },
    { name: "Kyat", code: "MMK",  minor_unit: 2 },
    { name: "Lari", code: "GEL", minor_unit: 2 },
    { name: "Latvian Lats", code: "LVL", minor_unit: 2 },
    { name: "Lebanese Pound", code: "LBP", minor_unit: 2 },
    { name: "Lek", code: "ALL", minor_unit: 2 },
    { name: "Lempira", code: "HNL", minor_unit: 2 },
    { name: "Leone", code: "SLL", minor_unit: 2 },
    { name: "Liberian Dollar", code: "LRD", minor_unit: 2 },
    { name: "Libyan Dinar", code: "LYD", minor_unit: 3 },
    { name: "Lilangeni", code: "SZL", minor_unit: 2 },
    { name: "Lithuanian Litas", code: "LTL", minor_unit: 2 },
    { name: "Loti", code: "LSL", minor_unit: 2 },
    { name: "Malagasy Ariary", code: "MGA", minor_unit: 2 },
    { name: "Malaysian Ringgit", code: "MYR", minor_unit: 2 },
    { name: "Mauritius Rupee", code: "MUR", minor_unit: 2 },
    { name: "Mexican Peso", code: "MXN", minor_unit: 2 },
    { name: "Mexican Unidad de Inversion (UDI)", code: "MXV", minor_unit: 2 },
    { name: "Moldovan Leu", code: "MDL", minor_unit: 2 },
    { name: "Moroccan Dirham", code: "MAD",  minor_unit: 2 },
    { name: "Mozambique Metical", code: "MZN",  minor_unit: 2 },
    { name: "Mvdol", code: "BOV", minor_unit: 2 },
    { name: "Naira", code: "NGN",  minor_unit: 2 },
    { name: "Nakfa", code: "ERN", minor_unit: 2 },
    { name: "Namibia Dollar", code: "NAD",  minor_unit: 2 },
    { name: "Nepalese Rupee", code: "NPR",  minor_unit: 2 },
    { name: "Netherlands Antillean Guilder", code: "ANG", minor_unit: 2 },
    { name: "New Israeli Sheqel", code: "ILS", minor_unit: 2 },
    { name: "New Romanian Leu", code: "RON", minor_unit: 2 },
    { name: "New Taiwan Dollar", code: "TWD", minor_unit: 2 },
    { name: "New Zealand Dollar", code: "NZD", minor_unit: 2 },
    { name: "Ngultrum", code: "BTN", minor_unit: 2 },
    { name: "North Korean Won", code: "KPW", minor_unit: 2 },
    { name: "Norwegian Krone", code: "NOK", minor_unit: 2 },
    { name: "Nuevo Sol", code: "PEN",  minor_unit: 2 },
    { name: "Ouguiya", code: "MRO", minor_unit: 2 },
    { name: "Pakistan Rupee", code: "PKR",  minor_unit: 2 },
    { name: "Pataca", code: "MOP", minor_unit: 2 },
    { name: "Pa’anga", code: "TOP", minor_unit: 2 },
    { name: "Peso Convertible", code: "CUC", minor_unit: 2 },
    { name: "Peso Uruguayo", code: "UYU", minor_unit: 2 },
    { name: "Philippine Peso", code: "PHP",  minor_unit: 2 },
    { name: "Pound Sterling", code: "GBP", minor_unit: 2 },
    { name: "Pula", code: "BWP", minor_unit: 2 },
    { name: "Qatari Rial", code: "QAR",  minor_unit: 2 },
    { name: "Quetzal", code: "GTQ", minor_unit: 2 },
    { name: "Rand", code: "ZAR",  minor_unit: 2 },
    { name: "Rial Omani", code: "OMR",  minor_unit: 3 },
    { name: "Riel", code: "KHR", minor_unit: 2 },
    { name: "Rufiyaa", code: "MVR", minor_unit: 2 },
    { name: "Rupiah", code: "IDR", minor_unit: 2 },
    { name: "Russian Ruble", code: "RUB", minor_unit: 2 },
    { name: "Rwanda Franc", code: "RWF", minor_unit: 0 },
    { name: "Saint Helena Pound", code: "SHP", minor_unit: 2 },
    { name: "Saudi Riyal", code: "SAR", minor_unit: 2 },
    { name: "Serbian Dinar", code: "RSD", minor_unit: 2 },
    { name: "Seychelles Rupee", code: "SCR", minor_unit: 2 },
    { name: "Singapore Dollar", code: "SGD", minor_unit: 2 },
    { name: "Solomon Islands Dollar", code: "SBD", minor_unit: 2 },
    { name: "Som", code: "KGS", minor_unit: 2 },
    { name: "Somali Shilling", code: "SOS", minor_unit: 2 },
    { name: "Somoni", code: "TJS", minor_unit: 2 },
    { name: "South Sudanese Pound", code: "SSP", minor_unit: 2 },
    { name: "Sri Lanka Rupee", code: "LKR", minor_unit: 2 },
    { name: "Sudanese Pound", code: "SDG", minor_unit: 2 },
    { name: "Surinam Dollar", code: "SRD", minor_unit: 2 },
    { name: "Swedish Krona", code: "SEK", minor_unit: 2 },
    { name: "Swiss Franc", code: "CHF", minor_unit: 2 },
    { name: "Syrian Pound", code: "SYP", minor_unit: 2 },
    { name: "Taka", code: "BDT", minor_unit: 2 },
    { name: "Tala", code: "WST", minor_unit: 2 },
    { name: "Tanzanian Shilling", code: "TZS", minor_unit: 2 },
    { name: "Tenge", code: "KZT", minor_unit: 2 },
    { name: "Trinidad and Tobago Dollar", code: "TTD", minor_unit: 2 },
    { name: "Tugrik", code: "MNT", minor_unit: 2 },
    { name: "Tunisian Dinar", code: "TND", minor_unit: 3 },
    { name: "Turkish Lira", code: "TRY", minor_unit: 2 },
    { name: "Turkmenistan New Manat", code: "TMT", minor_unit: 2 },
    { name: "UAE Dirham", code: "AED", minor_unit: 2 },
    { name: "Uganda Shilling", code: "UGX", minor_unit: 0 },
    { name: "Unidad de Fomento", code: "CLF", minor_unit: 0 },
    { name: "Unidad de Valor Real", code: "COU", minor_unit: 2 },
    { name: "Uruguay Peso en Unidades Indexadas (URUIURUI)", code: "UYI", minor_unit: 0 },
    { name: "US Dollar", code: "USD", minor_unit: 2 },
    { name: "Uzbekistan Sum", code: "UZS", minor_unit: 2 },
    { name: "Vatu", code: "VUV", minor_unit: 0 },
    { name: "WIR Euro", code: "CHE", minor_unit: 2 },
    { name: "WIR Franc", code: "CHW", minor_unit: 2 },
    { name: "Won", code: "KRW", minor_unit: 0 },
    { name: "Yemeni Rial", code: "YER", minor_unit: 2 },
    { name: "Yen", code: "JPY", minor_unit: 0 },
    { name: "Yuan Renminbi", code: "CNY", minor_unit: 2 },
    { name: "Zambian Kwacha", code: "ZMW", minor_unit: 2 },
    { name: "Zimbabwe Dollar", code: "ZWL", minor_unit: 2 },
    { name: "Zloty", code: "PLN",  minor_unit: 2 }
  ])